/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vues.Components;
import Backend.Note.NoteManagement;
import Backend.Note.Note;
import javax.swing.table.DefaultTableModel;
import Vues.Components.table.TableCustom;
import javax.swing.JOptionPane;

/**
 *
 * @author Thierry Christophe
 */
public class NoteVues extends javax.swing.JPanel {
   
    /**
     * Creates new form NoteVues
     */
    private static NoteManagement noteTraitement = new NoteManagement();
    private Note note = new Note();
    public NoteVues() {
        initComponents();
        jTable2.setModel(noteTraitement.liste());
        TableCustom.apply(jScrollPane2, TableCustom.TableType.MULTI_LINE);
        jComboBox1.setModel(noteTraitement.selectionEleve());
        jComboBox2.setModel(noteTraitement.selectionMat());
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn_Ajout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        Btn_update = new javax.swing.JButton();
        Btn_update1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Btn_Ajout.setBackground(new java.awt.Color(51, 102, 255));
        Btn_Ajout.setText("Ajouter");
        Btn_Ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AjoutActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 2, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Géstion de note");

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item1", "Item2", "Item23" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable2MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item1", "Item2", "Item23" }));

        Btn_update.setBackground(new java.awt.Color(51, 102, 255));
        Btn_update.setText("modifier");
        Btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_updateActionPerformed(evt);
            }
        });

        Btn_update1.setBackground(new java.awt.Color(51, 102, 255));
        Btn_update1.setText("supprimer");
        Btn_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_update1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Note ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Année Scolaire");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numèro Matière");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Numèro élève");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(Btn_Ajout)
                        .addGap(72, 72, 72)
                        .addComponent(Btn_update)
                        .addGap(64, 64, 64)
                        .addComponent(Btn_update1)))
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Ajout)
                    .addComponent(Btn_update)
                    .addComponent(Btn_update1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AjoutActionPerformed
        // TODO add your handling code here:
      if(Integer.parseInt(jSpinner1.getValue().toString())<0||Integer.parseInt(jSpinner1.getValue().toString())>20){
            JOptionPane.showInternalMessageDialog(null, "Le note doit être inferieurou egale a 20 et positive");
      }else{ 
            note.setAllAttribut(jComboBox1.getSelectedItem().toString(), jComboBox2.getSelectedItem().toString()
                    ,jTextField3.getText(),Integer.parseInt(jSpinner1.getValue().toString()));
            if(noteTraitement.insertion(note)){
                JOptionPane.showInternalMessageDialog(null, "Insertion réussi");
                jTextField3.setText("");
                jSpinner1.setValue(0);
                jTable2.setModel(noteTraitement.liste());
            }else{
                JOptionPane.showInternalMessageDialog(null, "Echec d'insertion");
            }
      }
    }//GEN-LAST:event_Btn_AjoutActionPerformed

    private void Btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_updateActionPerformed
        // TODO add your handling code here:
     
        if(Integer.parseInt(jSpinner1.getValue().toString())<0||Integer.parseInt(jSpinner1.getValue().toString())>20){
            JOptionPane.showInternalMessageDialog(null, "Le note doit être inferieurou egale a 20 et positive");
        }else{
                note.setAllAttribut(jComboBox1.getSelectedItem().toString(), jComboBox2.getSelectedItem().toString()
                                ,jTextField3.getText(),Integer.parseInt(jSpinner1.getValue().toString()));
              
              if(noteTraitement.update(note)){
                    JOptionPane.showInternalMessageDialog(null, "Modification réussi");
                    jTextField3.setText("");
                    jSpinner1.setValue(0);
                    jTable2.setModel(noteTraitement.liste());
              }else{
                  JOptionPane.showInternalMessageDialog(null, "Echec de modification");
              }
        }      
    
    }//GEN-LAST:event_Btn_updateActionPerformed

    private void Btn_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_update1ActionPerformed
        // TODO add your handling code here:
         try{
              int i = jTable2.getSelectedRow();
              note.setAllAttribut(jTable2.getModel().getValueAt(i, 0).toString(), jTable2.getModel().getValueAt(i, 1).toString()
                                ,jTable2.getModel().getValueAt(i, 2).toString(),Integer.parseInt(jTable2.getModel().getValueAt(i,3).toString()));
              int message =  JOptionPane.showConfirmDialog(this, "Vous voulez le supprimer", "confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
              if(message==JOptionPane.YES_OPTION){  
                    if(noteTraitement.delete(note)){
                          JOptionPane.showInternalMessageDialog(null, "Suppréssion  réussi");
                    
                          jTable2.setModel(noteTraitement.liste());
                    }else{
                        JOptionPane.showInternalMessageDialog(null, "Echec de suppréssion");
                    }
               }
              
        }catch(Exception e){
               JOptionPane.showInternalMessageDialog(null, "Veuillez selection le table avant de modifier");   
        }
    }//GEN-LAST:event_Btn_update1ActionPerformed

    private void jTable2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseReleased
        // TODO add your handling code here:
           //Eviter la modification du clé primaire
     
        int i = jTable2.getSelectedRow();
              
                jComboBox1.setSelectedItem(jTable2.getModel().getValueAt(i, 0).toString());
                jComboBox2.setSelectedItem(jTable2.getModel().getValueAt(i, 1).toString());
                jTextField3.setText(jTable2.getModel().getValueAt(i, 2).toString());
                jSpinner1.setValue(Integer.parseInt(jTable2.getModel().getValueAt(i,3).toString()));
    }//GEN-LAST:event_jTable2MouseReleased
    public static void l(){
        System.out.print("Je suis dans eleve");
    }
    public static void UpdateData(){
        jComboBox1.setModel(noteTraitement.selectionEleve());
        jComboBox2.setModel(noteTraitement.selectionMat());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Ajout;
    private javax.swing.JButton Btn_update;
    private javax.swing.JButton Btn_update1;
    private static javax.swing.JComboBox<String> jComboBox1;
    private static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
